(function(){
var API='https://api.anihub.in.ua';
var UA='Mozilla/5.0 (iPhone; CPU iPhone OS 18_0 like Mac OS X) AppleWebKit/605.1.15 Version/18.0 Mobile/15E148 Safari/604.1';
var FALLBACK='https://raw.githubusercontent.com/arranoust/MiraiExt-SkyStream/main/banner.jpg';
function H(ref,accept,extra){var h={'User-Agent':UA,'Accept':accept||'application/json,text/plain,*/*','Referer':ref||manifest.baseUrl+'/'};if(extra)for(var k in extra)h[k]=extra[k];return h}
function dec(s){return String(s==null?'':s).replace(/\\u0026/g,'&').replace(/\\\//g,'/').replace(/&amp;/g,'&').replace(/&quot;/g,'"').replace(/&#39;|&#039;/g,"'")}
function txt(s){return dec(s).replace(/<br\s*\/?>/gi,' ').replace(/<[^>]+>/g,'').replace(/\s+/g,' ').trim()}
function pick(o,ks,d){for(var i=0;i<ks.length;i++){var v=o&&o[ks[i]];if(v!==undefined&&v!==null&&v!=='')return v}return d}
function n(v,d){var x=parseInt(v,10);return isNaN(x)?d:x}
async function raw(u,h){try{var r=await http_get(u,h||H()),b=r&&typeof r.body==='string'?r.body:'';return{body:b,status:r&&((r.statusCode||r.status))||0,error:''}}catch(e){return{body:'',status:0,error:String(e)}}}
async function json(u,h){var r=await raw(u,h||H(manifest.baseUrl+'/'));if(!r.body)throw new Error('HTTP '+r.status+' '+u);return JSON.parse(r.body)}
function abs(u,base){u=dec(u).trim();if(!u)return'';if(/^https?:\/\//i.test(u))return u;if(u.indexOf('//')===0)return'https:'+u;try{return new URL(u,base||manifest.baseUrl+'/').toString()}catch(e){return''}}
function titleOf(x){var t=pick(x,['title_ukrainian','title_ua','name_uk','name','title'],null);if(t)return txt(t);var ts=x&&x.titles||{};return txt(pick(ts,['ukrainian','uk','ua','english','original'],'AniHub'))}
function idOf(x){return n(pick(x,['id','anime_id'],0),0)}
function pageUrl(x){var id=idOf(x),s=String(pick(x,['slug'],'')||'');if(s&&id)return manifest.baseUrl+'/anime/'+s+'-'+id;if(s)return manifest.baseUrl+'/anime/'+s;return manifest.baseUrl+'/anime/'+id}
function posterOf(x){var c=[pick(x,['poster_url','poster','image_url','image','cover_url','cover'],''),x&&x.images&&pick(x.images,['poster','large','medium','original'],'')];for(var i=0;i<c.length;i++){var u=abs(c[i]);if(u)return u}return FALLBACK}
function descOf(x){return txt(pick(x,['description_ukrainian','description_ua','description','synopsis','overview'],'')||'')}
function epCount(x){return n(pick(x,['episodes_count','episodes','episode_count','episodes_total'],1),1)||1}
function item(x){return new MultimediaItem({title:titleOf(x),url:pageUrl(x),posterUrl:posterOf(x),type:'anime'})}
function arrFrom(d){if(Array.isArray(d))return d;if(d&&Array.isArray(d.items))return d.items;if(d&&Array.isArray(d.results))return d.results;if(d&&Array.isArray(d.anime))return d.anime;if(d&&d.data)return arrFrom(d.data);return[]}
async function section(path){try{var a=arrFrom(await json(API+path)),o=[];for(var i=0;i<a.length&&i<20;i++)o.push(item(a[i]));return o}catch(e){console.log('[AniHub v12][section] '+String(e));return[]}}
async function getHome(cb){try{var j=await Promise.all([section('/anime/newest?limit=20'),section('/anime/popular?limit=20'),section('/anime/seasonal?limit=20'),section('/anime?ordering=-updated_at&page=1&page_size=20&has_ukrainian_dub=true')]),d={};if(j[0].length)d['🆕 Новинки AniHub']=j[0];if(j[1].length)d['🔥 Популярне']=j[1];if(j[2].length)d['🌸 Поточний сезон']=j[2];if(j[3].length)d['🇺🇦 Українською']=j[3];cb({success:true,data:d})}catch(e){cb({success:false,error:'AniHub v12 getHome: '+String(e)})}}
async function search(q,cb){try{var a=arrFrom(await json(API+'/anime?search='+encodeURIComponent(q)+'&page=1&page_size=20&ordering=-rating')),o=[];for(var i=0;i<a.length&&i<20;i++)o.push(item(a[i]));if(!o.length)return cb({success:false,error:'Нічого не знайдено.'});cb({success:true,data:o})}catch(e){cb({success:false,error:'AniHub v12 search: '+String(e)})}}
function idFromPage(u){var m=String(u||'').match(/-(\d+)(?:[/?#]|$)/);if(m)return n(m[1],0);m=String(u||'').match(/\/anime\/(\d+)(?:[/?#]|$)/);return m?n(m[1],0):0}
function pack(page,ep){return'anihub:episode:'+encodeURIComponent(JSON.stringify({page:page,episode:ep}))}
function unpack(s){try{return JSON.parse(decodeURIComponent(String(s||'').slice('anihub:episode:'.length)))}catch(e){return null}}
function meta(s,p){var m=String(s||'').match(new RegExp('<meta[^>]+property=["\\\']'+p+'["\\\'][^>]+content=["\\\']([^"\\\']+)["\\\']','i'));return m?dec(m[1]):''}
async function load(url,cb){try{var id=idFromPage(url),x=id?await json(API+'/anime/'+id):null,p=await raw(url,H(url,'text/html,*/*')),html=p.body||'',poster=x?posterOf(x):(abs(meta(html,'og:image'))||FALLBACK),count=x?epCount(x):1,eps=[];for(var i=1;i<=count;i++)eps.push(new Episode({name:'Серія '+i,url:pack(url,i),season:1,episode:i,dubStatus:'dubbed',posterUrl:poster}));cb({success:true,data:new MultimediaItem({title:x?titleOf(x):txt(meta(html,'og:title')||'AniHub'),url:url,posterUrl:poster,bannerUrl:poster,type:'anime',description:x?descOf(x):'',episodes:eps})})}catch(e){cb({success:false,error:'AniHub v12 load: '+String(e)})}}
function attr(tag,name){var r=new RegExp('(?:^|\\s)'+name+'\\s*=\\s*(["\\\'])(.*?)\\1','i'),m=String(tag||'').match(r);return m?dec(m[2]):''}
function provider(u){u=String(u||'');if(/uacdn\.online/i.test(u))return'UACDN';if(/ashdi\.vip/i.test(u))return'ASHDI';if(/fenix/i.test(u))return'FENIX';if(/moon/i.test(u))return'MOON';return'OTHER'}
function usefulPlayer(u){return /uacdn\.online|ashdi\.vip|fenix|moonanime/i.test(String(u||''))}
function playerUrls(s,base){var out=[],seen={},tags=String(s||'').match(/<iframe\b[^>]*>/ig)||[],names=['data-src','src','data-url','data-player','data-frame','data-video'];for(var i=0;i<tags.length;i++)for(var j=0;j<names.length;j++){var r=attr(tags[i],names[j]),u=abs(r,base);if(u&&usefulPlayer(u)&&!seen[u]){seen[u]=1;out.push(u)}}var re=/(https?:\\?\/\\?\/[^"'\s<>]+)/ig,m;while((m=re.exec(String(s||'')))){var u2=dec(m[1]).replace(/\\\//g,'/').replace(/[),;]+$/,'');if(usefulPlayer(u2)&&!seen[u2]){seen[u2]=1;out.push(u2)}}return out}
function headers(ref){var h={'Referer':ref||manifest.baseUrl+'/','User-Agent':UA};try{h.Origin=new URL(ref||manifest.baseUrl+'/').origin}catch(e){}return h}
function host(u){try{return new URL(u).hostname}catch(e){return'?'}}
async function probe(u,ref){if(!/^https?:\/\//i.test(String(u||'')))return{ok:false,status:0,why:'bad-url'};if(/\.mp4(?:[?#]|$)/i.test(u))return{ok:true,status:0,why:'mp4'};if(!/\.m3u8(?:[?#]|$)/i.test(u))return{ok:false,status:0,why:'not-media'};var r=await raw(u,H(ref,'application/vnd.apple.mpegurl,application/x-mpegURL,text/plain,*/*'));var body=String(r.body||'');var ok=(r.status===200||r.status===206||r.status===0)&&body.indexOf('#EXTM3U')>=0;return{ok:ok,status:r.status,why:body.indexOf('#EXTM3U')>=0?'m3u8':(r.error||'no-extm3u')}
async function addChecked(out,u,label,ref,diag){u=dec(String(u||'')).trim().replace(/\\\//g,'/');var p=await probe(u,ref);diag.push(label+' '+host(u)+' p='+p.status+' '+p.why);if(p.ok)out.push(new StreamResult({url:u,source:'V12 '+label+' ['+host(u)+']',headers:headers(ref)}))}
function normQuality(q,u){var s=String(q||'')+' '+String(u||'');if(/2160|4k|uhd/i.test(s))return'2160p';if(/1440/i.test(s))return'1440p';if(/1080|fhd/i.test(s))return'1080p';if(/720/i.test(s))return'720p';if(/480/i.test(s))return'480p';if(/360/i.test(s))return'360p';return'Auto'}
async function addFileChecked(out,file,label,ref,diag){var r=dec(String(file||'').trim()),m,re=/\[([^\]]+)\](https?:\/\/[^,\s]+)/g,a=[],seen={};while((m=re.exec(r))!==null){var u=dec(m[2]),q=normQuality(m[1],u);if(!seen[u]){seen[u]=1;a.push({u:u,q:q})}}if(!a.length&&/^https?:\/\//i.test(r))a.push({u:r,q:normQuality('',r)});for(var i=0;i<a.length&&i<4;i++)await addChecked(out,a[i].u,label+(a[i].q!=='Auto'?' '+a[i].q:''),ref,diag)}
function playerFileValue(ph){var m=/\bfile\s*:/.exec(ph||'');if(!m)return null;var i=m.index+m[0].length,nx=ph.length;while(i<nx&&/\s/.test(ph.charAt(i)))i++;if(i>=nx)return null;var q=ph.charAt(i);if(q==='"'||q==="'"||q==='`'){i++;var out='',esc=false;for(;i<nx;i++){var c=ph.charAt(i);if(esc){out+=c;esc=false;continue}if(c==='\\'){esc=true;out+=c;continue}if(c===q)break;out+=c}return dec(out).replace(/\\(["'\/])/g,'$1')}if(q==='['){var st=i,dep=0,str='',esc2=false;for(;i<nx;i++){var ch=ph.charAt(i);if(str){if(esc2){esc2=false;continue}if(ch==='\\'){esc2=true;continue}if(ch===str)str='';continue}if(ch==='"'||ch==="'"||ch==='`'){str=ch;continue}if(ch==='[')dep++;else if(ch===']'){dep--;if(dep===0)return dec(ph.slice(st,i+1))}}}return null}
function flat(nod,o,path,pos){path=path||[];if(!nod)return;if(Array.isArray(nod)){for(var i=0;i<nod.length;i++)flat(nod[i],o,path,i+1);return}if(typeof nod!=='object')return;var title=txt(nod.title||''),next=path;if(nod.folder&&title)next=path.concat([title]);if(nod.file){var nums=title.match(/\d{1,3}/g),ep=nums&&nums.length?parseInt(nums[nums.length-1],10):(pos||1);o.push({title:title,number:ep,file:dec(nod.file),group:path.join(' › ')})}if(nod.folder)flat(nod.folder,o,next,1)}
function uacdnPayload(s){var m=String(s||'').match(/window\.__PLAYER_PAYLOAD__\s*=\s*(\{[\s\S]*?\});/);if(!m)return null;try{return JSON.parse(m[1])}catch(e){return null}}
async function resolveUacdn(player,page,ep,diag){var out=[],r=await raw(player,H(page,'text/html,application/xhtml+xml,*/*')),p=r.body?uacdnPayload(r.body):null;diag.push('UACDN player='+r.status+' payload='+(p?1:0));if(!p)return out;var tr=Array.isArray(p.translations)?p.translations.slice():[];if(!tr.length)tr=[{id:p.translate,title:p.translateTitle||'UA'}];for(var i=0;i<tr.length&&i<4;i++){var t=tr[i];if(/субтит|\bsub\b|subbed/i.test(String(t.title||'')))continue;try{var season=parseInt(p.season,10)||1,body=JSON.stringify({id:parseInt(p.id,10)||0,translation:parseInt(t.id,10)||parseInt(p.translate,10)||0,season_number:p.is_serial?season:null,episode_number:p.is_serial?ep:null,force_cdn:String(p.force_cdn||''),turnstile_token:''}),api=new URL('/api/player/files',player).toString(),hs={'User-Agent':UA,'Accept':'application/json','Content-Type':'application/json','Referer':player,'Origin':new URL(player).origin},rr=await http_post(api,hs,body),st=rr&&((rr.statusCode||rr.status))||0,text=rr&&typeof rr.body==='string'?rr.body:'';diag.push('UACDN api='+st+' s='+season+' e='+ep+' body='+(text?1:0));if(!text)continue;var j=JSON.parse(text),f=String(j.file||'');if(f)await addFileChecked(out,f,'UACDN '+txt(t.title||p.translateTitle||'UA'),player,diag)}catch(e){diag.push('UACDN err='+String(e).slice(0,80))}}return out}
async function resolveAshdi(player,page,ep,diag){var out=[],r=await raw(player,H(page,'text/html,application/xhtml+xml,*/*')),pf=r.body?playerFileValue(r.body):null;diag.push('ASHDI player='+r.status+' file='+(pf?1:0));if(!pf)return out;if(/^https?:\/\//i.test(pf)){if(ep===1)await addFileChecked(out,pf,'ASHDI',player,diag);return out}try{var cfg=JSON.parse(pf),a=[];flat(cfg,a,[],1);diag.push('ASHDI entries='+a.length+' ep='+ep);for(var i=0;i<a.length;i++)if(a[i].number===ep)await addFileChecked(out,a[i].file,'ASHDI '+txt(a[i].group||a[i].title||''),player,diag)}catch(e){diag.push('ASHDI parse='+String(e).slice(0,80))}return out}
function assignedJson(s,marker){var p=String(s||'').indexOf(marker);if(p<0)return'';var a=String(s).slice(p+marker.length),st=a.indexOf('{');if(st<0)return'';var d=0,q=false,e=false;for(var i=st;i<a.length;i++){var c=a.charAt(i);if(q){if(e)e=false;else if(c==='\\')e=true;else if(c==='"')q=false;continue}if(c==='"'){q=true;continue}if(c==='{')d++;else if(c==='}'&&--d===0)return a.slice(st,i+1)}return''}
async function resolveFenix(player,page,ep,diag){var out=[],r=await raw(player,H(page,'text/html,application/xhtml+xml,*/*')),s=r.body||'',pj=assignedJson(s,'window.FENIX_PLAYLIST')||assignedJson(s,'FENIX_PLAYLIST');diag.push('FENIX player='+r.status+' playlist='+(pj?1:0));if(!pj)return out;try{var pl=JSON.parse(pj),list=(pl.episodes||[]).concat(pl.mini_episodes||[]),entry=null;for(var i=0;i<list.length;i++){var en=n(pick(list[i],['number','episode','episode_number'],0),0);if(en===ep){entry=list[i];break}}diag.push('FENIX episodes='+list.length+' match='+(entry?1:0));if(!entry&&list.length===1)entry=list[0];if(!entry)return out;var tracks=entry.tracks||entry.sources||[];for(var j=0;j<tracks.length&&j<4;j++){var tr=tracks[j]||{},u=abs(pick(tr,['hls_url','url','src','file'],''),player);if(u)await addChecked(out,u,'FENIX'+(tr.label?' '+tr.label:''),player,diag)}}catch(e){diag.push('FENIX parse='+String(e).slice(0,80))}return out}
async function resolvePlayer(u,page,ep,diag){var p=provider(u);diag.push('PLAYER '+p+' '+host(u));if(p==='UACDN')return await resolveUacdn(u,page,ep,diag);if(p==='ASHDI')return await resolveAshdi(u,page,ep,diag);if(p==='FENIX')return await resolveFenix(u,page,ep,diag);diag.push(p+' unsupported');return[]}
function dedupe(a){var o=[],s={};for(var i=0;i<a.length;i++){var u=String(a[i]&&a[i].url||'');if(u&&!s[u]){s[u]=1;o.push(a[i])}}return o}
async function loadStreams(url,cb){try{var info=unpack(String(url||''));if(!info||!info.page)return cb({success:false,error:'AniHub v12 DEBUG: bad episode token'});var ep=n(info.episode,1),diag=[],page=await raw(info.page,H(info.page,'text/html,application/xhtml+xml,*/*')),players=playerUrls(page.body||'',info.page),out=[];diag.push('PAGE='+page.status+' players='+players.length+' ep='+ep);for(var i=0;i<players.length&&i<8;i++){var got=await resolvePlayer(players[i],info.page,ep,diag);for(var g=0;g<got.length;g++)out.push(got[g])}out=dedupe(out);console.log('[AniHub v12 DEBUG] '+diag.join(' | '));if(!out.length)return cb({success:false,error:'AniHub v12 DEBUG: '+diag.slice(0,8).join(' | ')});cb({success:true,data:out.slice(0,3)})}catch(e){cb({success:false,error:'AniHub v12 DEBUG FATAL: '+String(e)})}}
globalThis.getHome=getHome;globalThis.search=search;globalThis.load=load;globalThis.loadStreams=loadStreams;
}());