(function(){
var API='https://api.anihub.in.ua';
var INTERNAL='https://anihub.in.ua/api';
var UA='Mozilla/5.0 (iPhone; CPU iPhone OS 18_0 like Mac OS X) AppleWebKit/605.1.15 Version/18.0 Mobile/15E148 Safari/604.1';
var FALLBACK='https://raw.githubusercontent.com/arranoust/MiraiExt-SkyStream/main/banner.jpg';
function H(ref,accept,extra){var h={'User-Agent':UA,'Accept':accept||'application/json,text/plain,*/*','Referer':ref||manifest.baseUrl+'/'};try{h.Origin=new URL(ref||manifest.baseUrl+'/').origin}catch(e){h.Origin=manifest.baseUrl}if(extra)for(var k in extra)h[k]=extra[k];return h}
function dec(s){return String(s==null?'':s).replace(/\\u0026/g,'&').replace(/\\\//g,'/').replace(/&amp;/g,'&').replace(/&quot;/g,'"').replace(/&#39;|&#039;/g,"'")}
function txt(s){return dec(s).replace(/<br\s*\/?>/gi,' ').replace(/<[^>]+>/g,'').replace(/\s+/g,' ').trim()}
function pick(o,keys,d){for(var i=0;i<keys.length;i++){var v=o&&o[keys[i]];if(v!==undefined&&v!==null&&v!=='')return v}return d}
function n(v,d){var x=parseInt(v,10);return isNaN(x)?d:x}
async function raw(u,h){try{var r=await http_get(u,h||H()),b=r&&typeof r.body==='string'?r.body:'';return{body:b,status:r&&((r.statusCode||r.status))||0}}catch(e){return{body:'',status:0,error:String(e)}}}
async function json(u,h){var r=await raw(u,h||H(manifest.baseUrl+'/'));if(!r.body)throw new Error('HTTP '+r.status+' '+u);try{return JSON.parse(r.body)}catch(e){throw new Error('JSON parse '+u+': '+String(e))}}
function abs(u,base){u=dec(u).trim();if(!u)return'';if(/^https?:\/\//i.test(u))return u;if(u.indexOf('//')===0)return'https:'+u;try{return new URL(u,base||manifest.baseUrl+'/').toString()}catch(e){return''}}
function titleOf(x){var t=pick(x,['title_ukrainian','title_ua','name_uk','name','title'],null);if(t)return txt(t);var ts=x&&x.titles||{};return txt(pick(ts,['ukrainian','uk','ua','english','original'],'AniHub'))}
function slugOf(x){return String(pick(x,['slug'],'')||'')}
function idOf(x){return n(pick(x,['id','anime_id'],0),0)}
function pageUrl(x){var id=idOf(x),slug=slugOf(x);if(slug&&id)return manifest.baseUrl+'/anime/'+slug+'-'+id;if(slug)return manifest.baseUrl+'/anime/'+slug;return manifest.baseUrl+'/anime/'+id}
function posterOf(x){var c=[pick(x,['poster_url','poster','image_url','image','cover_url','cover'],''),x&&x.images&&pick(x.images,['poster','large','medium','original'],''),x&&x.poster&&pick(x.poster,['url','large','original'],'')];var ss=x&&x.screenshots;if(Array.isArray(ss)&&ss.length)c.push(typeof ss[0]==='string'?ss[0]:pick(ss[0],['url','image','src'],''));for(var i=0;i<c.length;i++){var u=abs(c[i],manifest.baseUrl+'/');if(u)return u}return FALLBACK}
function descOf(x){return txt(pick(x,['description_ukrainian','description_ua','description','synopsis','overview'],'')||'')}
function genresOf(x){var g=x&&x.genres;if(!Array.isArray(g))return'';return g.map(function(v){return txt(typeof v==='string'?v:pick(v,['name_ukrainian','name','title'],''))}).filter(Boolean).join(', ')}
function epCount(x){return n(pick(x,['episodes_count','episodes','episode_count','episodes_total'],1),1)||1}
function seasonNo(x){return n(pick(x,['season','season_number'],1),1)||1}
function withMetaDesc(x){var d=descOf(x),bits=[],y=pick(x,['year'],null),st=pick(x,['status'],null),g=genresOf(x);if(y)bits.push(String(y));if(st)bits.push(String(st));if(g)bits.push(g);return[d,bits.join(' · ')].filter(Boolean).join('\n\n')}
function item(x){return new MultimediaItem({title:titleOf(x),url:pageUrl(x),posterUrl:posterOf(x),type:'anime'})}
function items(a,limit){a=Array.isArray(a)?a:[];var o=[];for(var i=0;i<a.length&&(limit==null||i<limit);i++)o.push(item(a[i]));return o}
function arrFrom(d){if(Array.isArray(d))return d;if(d&&Array.isArray(d.items))return d.items;if(d&&Array.isArray(d.results))return d.results;if(d&&Array.isArray(d.anime))return d.anime;if(d&&d.data)return arrFrom(d.data);return[]}
async function section(path,limit){try{return items(arrFrom(await json(API+path)),limit)}catch(e){console.log('[AniHub v5][section] '+path+' '+String(e));return[]}}
async function getHome(cb){try{var jobs=await Promise.all([section('/anime/newest?limit=20',20),section('/anime/popular?limit=20',20),section('/anime/seasonal?limit=20',20),section('/anime?ordering=-updated_at&page=1&page_size=20&has_ukrainian_dub=true',20),section('/anime?type=movie&ordering=-rating&page=1&page_size=20',20)]),data={};if(jobs[0].length)data['🆕 Новинки AniHub']=jobs[0];if(jobs[1].length)data['🔥 Популярне']=jobs[1];if(jobs[2].length)data['🌸 Поточний сезон']=jobs[2];if(jobs[3].length)data['🇺🇦 Українською']=jobs[3];if(jobs[4].length)data['🎬 Фільми']=jobs[4];if(!Object.keys(data).length)return cb({success:false,error:'AniHub: каталог тимчасово недоступний.'});cb({success:true,data:data})}catch(e){cb({success:false,error:'AniHub getHome: '+String(e)})}}
async function search(q,cb){try{var d=await json(API+'/anime?search='+encodeURIComponent(q)+'&page=1&page_size=20&ordering=-rating'),a=arrFrom(d);if(!a.length)return cb({success:false,error:'Нічого не знайдено.'});cb({success:true,data:items(a,20)})}catch(e){cb({success:false,error:'AniHub search: '+String(e)})}}
function idFromPage(u){var m=String(u||'').match(/-(\d+)(?:[/?#]|$)/);if(m)return n(m[1],0);var m2=String(u||'').match(/\/anime\/(\d+)(?:[/?#]|$)/);return m2?n(m2[1],0):0}
function pack(page,ep,season){return'anihub:episode:'+encodeURIComponent(JSON.stringify({page:page,episode:ep,season:season||1}))}
function unpack(s){try{return JSON.parse(decodeURIComponent(String(s||'').slice('anihub:episode:'.length)))}catch(e){return null}}
function meta(s,p){var r=new RegExp('<meta[^>]+property=["\\\']'+p+'["\\\'][^>]+content=["\\\']([^"\\\']+)["\\\']','i'),m=String(s||'').match(r);if(!m){r=new RegExp('<meta[^>]+content=["\\\']([^"\\\']+)["\\\'][^>]+property=["\\\']'+p+'["\\\']','i');m=String(s||'').match(r)}return m?dec(m[1]):''}
function imageFromHtml(s){var u=meta(s,'og:image');return abs(u)||FALLBACK}
async function load(url,cb){try{var id=idFromPage(url),x=null;if(id){try{x=await json(API+'/anime/'+id)}catch(e){console.log('[AniHub v5][detail api] '+String(e))}}var page=await raw(url,H(url,'text/html,application/xhtml+xml,*/*')),html=page.body||'',title=x?titleOf(x):txt(meta(html,'og:title')||'AniHub'),poster=x?posterOf(x):imageFromHtml(html),count=x?epCount(x):1,season=x?seasonNo(x):1,eps=[];for(var i=1;i<=count;i++)eps.push(new Episode({name:'Серія '+i,url:pack(url,i,season),season:season,episode:i,dubStatus:'dubbed',posterUrl:poster}));cb({success:true,data:new MultimediaItem({title:title,url:url,posterUrl:poster,bannerUrl:poster,type:'anime',description:x?withMetaDesc(x):'',episodes:eps})})}catch(e){cb({success:false,error:'AniHub load: '+String(e)})}}
function sha256(ascii){function rr(v,a){return(v>>>a)|(v<<(32-a))}var mathPow=Math.pow,maxWord=mathPow(2,32),lengthProperty='length',i,j,result='',words=[],asciiBitLength=ascii[lengthProperty]*8,hash=sha256.h=sha256.h||[],k=sha256.k=sha256.k||[],primeCounter=k[lengthProperty],isComposite={};for(var candidate=2;primeCounter<64;candidate++){if(!isComposite[candidate]){for(i=0;i<313;i+=candidate)isComposite[i]=candidate;hash[primeCounter]=(mathPow(candidate,.5)*maxWord)|0;k[primeCounter++]=(mathPow(candidate,1/3)*maxWord)|0}}ascii+='\x80';while(ascii[lengthProperty]%64-56)ascii+='\x00';for(i=0;i<ascii[lengthProperty];i++){j=ascii.charCodeAt(i);if(j>>8)return'';words[i>>2]|=j<<((3-i)%4)*8}words[words.length]=((asciiBitLength/maxWord)|0);words[words.length]=asciiBitLength;for(j=0;j<words.length;){var w=words.slice(j,j+=16),h=hash.slice(0);for(i=0;i<64;i++){var w15=w[i-15],w2=w[i-2],a=h[0],e=h[4],temp1=h[7]+(rr(e,6)^rr(e,11)^rr(e,25))+((e&h[5])^((~e)&h[6]))+k[i]+(w[i]=(i<16)?w[i]:((w[i-16]+(rr(w15,7)^rr(w15,18)^(w15>>>3))+w[i-7]+(rr(w2,17)^rr(w2,19)^(w2>>>10)))|0)),temp2=(rr(a,2)^rr(a,13)^rr(a,22))+((a&h[1])^(a&h[2])^(h[1]&h[2]));h=[(temp1+temp2)|0,a,h[1],h[2],(h[3]+temp1)|0,h[4],h[5],h[6]]}for(i=0;i<8;i++)hash[i]=(hash[i]+h[i])|0}for(i=0;i<8;i++)for(j=3;j+1;j--){var b=(hash[i]>>(j*8))&255;result+=(b<16?'0':'')+b.toString(16)}return result}
function pad2(v){return v<10?'0'+v:String(v)}
function apiKey(offset){var d=new Date(Date.now()+(offset||0)*86400000),date=d.getUTCFullYear()+'-'+pad2(d.getUTCMonth()+1)+'-'+pad2(d.getUTCDate());return sha256('Ukr@in1anAn1me-S3curity-Key-2025_'+date)}
async function sources(id,season){var u=INTERNAL+'/anime/'+id+'/episode-sources?season='+encodeURIComponent(season||1),keys=[apiKey(0),apiKey(-1),apiKey(1)],last='';for(var i=0;i<keys.length;i++){var r=await raw(u,H(manifest.baseUrl+'/','application/json,text/plain,*/*',{'X-API-Key':keys[i],'X-Requested-With':'XMLHttpRequest'}));last=r.body||'';if(last){try{return JSON.parse(last)}catch(e){}}}throw new Error('episode-sources unavailable')}
function assignedJson(s,marker){var p=String(s||'').indexOf(marker);if(p<0)return'';var after=String(s).slice(p+marker.length),start=after.indexOf('{');if(start<0)return'';var depth=0,q=false,esc=false;for(var i=start;i<after.length;i++){var c=after.charAt(i);if(q){if(esc)esc=false;else if(c==='\\')esc=true;else if(c==='"')q=false;continue}if(c==='"'){q=true;continue}if(c==='{')depth++;else if(c==='}'){depth--;if(depth===0)return after.slice(start,i+1)}}return''}
function streamHeaders(ref){var h={'Referer':ref||manifest.baseUrl+'/','User-Agent':UA};try{h.Origin=new URL(ref||manifest.baseUrl+'/').origin}catch(e){}return h}
function addStream(out,u,source,ref){u=dec(u).trim().replace(/\\\//g,'/');if(!/^https?:\/\//i.test(u))return;if(!/\.(m3u8|mp4)(?:[?#]|$)/i.test(u))return;out.push(new StreamResult({url:u,source:source||'AniHub',headers:streamHeaders(ref)}))}
function fileValue(s){var m=String(s||'').match(/\bfile\s*:\s*(["'`])([\s\S]*?)\1/i);return m?dec(m[2]):''}
function qRank(q){var m=String(q||'').match(/(2160|1440|1080|720|480|360)/);return m?n(m[1],0):0}
function addFiles(out,file,source,ref){file=dec(file);var found=[],seen={},re=/\[([^\]]+)\](https?:\/\/[^,\s]+)/g,m;while((m=re.exec(file))){if(!seen[m[2]]){seen[m[2]]=1;found.push({q:m[1],u:m[2]})}}if(!found.length&&/^https?:\/\//i.test(file.trim()))found.push({q:'Auto',u:file.trim()});found.sort(function(a,b){return qRank(b.q)-qRank(a.q)});for(var i=0;i<found.length;i++)addStream(out,found[i].u,(source||'AniHub')+(found[i].q&&found[i].q!=='Auto'?' · '+found[i].q:''),ref)}
function directMedia(s){var out=[],seen={},re=/(https?:\\?\/\\?\/[^"'\s<>]+?\.(?:m3u8|mp4)(?:\?[^"'\s<>]*)?)/ig,m;while((m=re.exec(String(s||'')))){var u=dec(m[1]).replace(/\\\//g,'/');if(!seen[u]){seen[u]=1;out.push(u)}}return out}
function urlsFromText(s){var out=[],seen={},re=/(https?:\\?\/\\?\/[^"'\s<>]+)/ig,m;while((m=re.exec(String(s||'')))){var u=dec(m[1]).replace(/\\\//g,'/').replace(/[),;]+$/,'');if(/^https?:\/\//i.test(u)&&!seen[u]){seen[u]=1;out.push(u)}}return out}
function providerName(u,fallback){u=String(u||'').toLowerCase();if(u.indexOf('fenix')>=0)return'Fenix';if(u.indexOf('ashdi')>=0)return'ASHDI';if(u.indexOf('moon')>=0)return'MoonAnime';return fallback||'AniHub'}
function explicitEpisode(o){if(!o||typeof o!=='object')return null;var v=pick(o,['episode_number','episode','number','ep','episodeNumber'],null);if(v===null||v===undefined||v==='')return null;var x=parseInt(v,10);return isNaN(x)?null:x}
function collectCandidates(node,ep,out,seen,label,depth){if(depth>12||node==null)return;if(typeof node==='string'){var us=urlsFromText(node);for(var i=0;i<us.length;i++)if(!seen[us[i]]){seen[us[i]]=1;out.push({url:us[i],label:providerName(us[i],label)})}return}if(Array.isArray(node)){for(var a=0;a<node.length;a++)collectCandidates(node[a],ep,out,seen,label,depth+1);return}if(typeof node!=='object')return;var ownEp=explicitEpisode(node);if(ownEp!==null&&ownEp!==ep)return;var here=String(pick(node,['studio_name','studio','label','name','provider','player'],'')||label||'AniHub');for(var k in node){var v=node[k];if(typeof v==='string'&&/(url|src|file|link|iframe|vod|video|stream|hls)/i.test(k)){var u=abs(v,manifest.baseUrl+'/');if(u&&!seen[u]){seen[u]=1;out.push({url:u,label:providerName(u,here)})}}}for(var q in node)collectCandidates(node[q],ep,out,seen,here,depth+1)}
async function probeHls(u,ref){if(!/\.m3u8(?:[?#]|$)/i.test(u))return true;var r=await raw(u,H(ref,'application/vnd.apple.mpegurl,application/x-mpegURL,text/plain,*/*'));return (r.status===200||r.status===206)&&String(r.body||'').indexOf('#EXTM3U')>=0}
async function resolveFenix(u,studio,ep){var out=[],r=await raw(u,H(u,'text/html,application/xhtml+xml,*/*')),s=r.body||'';if(!s)return out;var aj=assignedJson(s,'window.FENIX_MEDIA_ACCESS'),pj=assignedJson(s,'window.FENIX_PLAYLIST');if(!pj)return out;try{var access=aj?JSON.parse(aj):{},pl=JSON.parse(pj),all=(pl.episodes||[]).concat(pl.mini_episodes||[]),entry=null;for(var i=0;i<all.length;i++){var en=n(pick(all[i],['number','episode','episode_number'],0),0);if(en===ep){entry=all[i];break}}if(!entry&&all.length===1)entry=all[0];if(!entry)return out;var tracks=entry.tracks||entry.sources||[],token=String(pick(access,['token','access_token','media_token'],'')||'');for(var j=0;j<tracks.length;j++){var tr=tracks[j]||{},hu=abs(pick(tr,['hls_url','url','src','file'],''),u);if(!hu)continue;try{var x=new URL(hu);if(token&&!x.searchParams.get('token'))x.searchParams.append('token',token);hu=x.toString()}catch(e){}var ok=await probeHls(hu,u);console.log('[AniHub v5][fenix probe] ep='+ep+' status='+(ok?'ok':'fail')+' '+hu.slice(0,100));if(ok)addStream(out,hu,'Fenix'+(tr.label?' · '+tr.label:''),u)}}catch(e){console.log('[AniHub v5][fenix parse] '+String(e))}return out}
async function resolveGeneric(u,studio,ep){if(/fenix/i.test(u))return await resolveFenix(u,studio,ep);var out=[];if(/\.(m3u8|mp4)(?:[?#]|$)/i.test(u)){if(await probeHls(u,u))addStream(out,u,studio,u);return out}var r=await raw(u,H(u,'text/html,application/xhtml+xml,*/*')),s=r.body||'';if(!s)return out;if(/fenix/i.test(s.slice(0,10000)))return await resolveFenix(u,studio,ep);var dm=directMedia(s);for(var i=0;i<dm.length;i++){if(await probeHls(dm[i],u))addStream(out,dm[i],studio,u)}var f=fileValue(s);if(f)addFiles(out,f,studio,u);return out}
function dedupe(a){var out=[],seen={};for(var i=0;i<a.length;i++){var u=String(a[i]&&a[i].url||'');if(!u||seen[u])continue;seen[u]=1;out.push(a[i])}return out}
async function loadStreams(url,cb){try{var token=String(url||'');if(token.indexOf('anihub:episode:')!==0)return cb({success:false,error:'AniHub: невідомий формат епізоду.'});var info=unpack(token);if(!info||!info.page)return cb({success:false,error:'AniHub: пошкоджений токен епізоду.'});var id=idFromPage(info.page),ep=n(info.episode,1),season=n(info.season,1);if(!id)return cb({success:false,error:'AniHub: не вдалося визначити ID тайтлу.'});var out=[],cand=[],seen={};try{var src=await sources(id,season);collectCandidates(src,ep,cand,seen,'AniHub',0)}catch(e){console.log('[AniHub v5][sources] '+String(e))}var page=await raw(info.page,H(info.page,'text/html,application/xhtml+xml,*/*'));if(page.body)collectCandidates(page.body,ep,cand,seen,'AniHub page',0);cand.sort(function(a,b){var af=/fenix/i.test(a.url)?0:/ashdi/i.test(a.url)?1:/moon/i.test(a.url)?2:3;var bf=/fenix/i.test(b.url)?0:/ashdi/i.test(b.url)?1:/moon/i.test(b.url)?2:3;return af-bf});var used={};for(var i=0;i<cand.length&&i<16;i++){var c=cand[i],u=c.url;if(!/^https?:\/\//i.test(u)||used[u])continue;used[u]=1;if(!/(fenix|ashdi|moon|player|embed|video|watch|vod|\.m3u8|\.mp4)/i.test(u))continue;var got=await resolveGeneric(u,c.label,ep);for(var g=0;g<got.length;g++)out.push(got[g]);if(out.length>=8)break}out=dedupe(out);console.log('[AniHub v5][streams] id='+id+' season='+season+' ep='+ep+' candidates='+cand.length+' streams='+out.length);if(!out.length)return cb({success:false,error:'AniHub v5: робочий відеопотік для цієї серії не знайдений.'});cb({success:true,data:out})}catch(e){console.log('[AniHub v5][streams fatal] '+String(e));cb({success:false,error:'AniHub v5 loadStreams: '+String(e)})}}
globalThis.getHome=getHome;globalThis.search=search;globalThis.load=load;globalThis.loadStreams=loadStreams;
}());
