
(function(){
var API='https://api.anihub.in.ua';
var UA='Mozilla/5.0 (iPhone; CPU iPhone OS 18_0 like Mac OS X) AppleWebKit/605.1.15 Version/18.0 Mobile/15E148 Safari/604.1';
var baseLoad=globalThis.load;
function n(v,d){var x=parseInt(v,10);return isNaN(x)?d:x}
function dec(s){return String(s==null?'':s).replace(/\\u0026/g,'&').replace(/\\\//g,'/').replace(/&amp;/g,'&').replace(/&quot;/g,'"')}
function txt(s){return dec(s).replace(/<[^>]+>/g,'').replace(/\s+/g,' ').trim()}
function pick(o,keys,d){for(var i=0;i<keys.length;i++){var v=o&&o[keys[i]];if(v!==undefined&&v!==null&&v!=='')return v}return d}
function titleOf(x){var t=pick(x,['title_ukrainian','title_ua','name_uk','name','title'],null);if(t)return txt(t);var ts=x&&x.titles||{};return txt(pick(ts,['ukrainian','uk','ua','english','original'],'AniHub'))}
function idOf(x){return n(pick(x,['id','anime_id'],0),0)}
function slugOf(x){return String(pick(x,['slug'],'')||'')}
function pageUrl(x){var id=idOf(x),slug=slugOf(x);if(slug&&id)return manifest.baseUrl+'/anime/'+slug+'-'+id;if(slug)return manifest.baseUrl+'/anime/'+slug;return manifest.baseUrl+'/anime/'+id}
function posterOf(x){var u=String(pick(x,['poster_url','poster','image_url','image','cover_url','cover'],'')||'');return u||'https://raw.githubusercontent.com/arranoust/MiraiExt-SkyStream/main/banner.jpg'}
async function getJson(u,headers){try{var r=await http_get(u,headers||{'User-Agent':UA,'Accept':'application/json'});if(!r||!r.body)return null;return JSON.parse(r.body)}catch(e){console.log('[AniHub related] '+u+' '+String(e));return null}}
function idFromPage(u){var m=String(u||'').match(/-(\d+)(?:[/?#]|$)/);if(m)return n(m[1],0);var m2=String(u||'').match(/\/anime\/(\d+)(?:[/?#]|$)/);return m2?n(m2[1],0):0}
async function findAniHubByMal(mal){var d=await getJson(API+'/anime?mal_id='+encodeURIComponent(mal)+'&page=1&page_size=1&has_ukrainian_dub=true');var a=d&&Array.isArray(d.items)?d.items:[];return a.length?a[0]:null}
async function recommendationsFor(x){var mal=n(x&&x.mal_id,0);if(!mal)return[];var rel=await getJson('https://api.jikan.moe/v4/anime/'+mal+'/relations',{'User-Agent':UA,'Accept':'application/json'});var groups=rel&&Array.isArray(rel.data)?rel.data:[],targets=[];for(var i=0;i<groups.length;i++){var relation=String(groups[i].relation||'').toLowerCase();if(relation!=='prequel'&&relation!=='sequel')continue;var entries=Array.isArray(groups[i].entry)?groups[i].entry:[];for(var j=0;j<entries.length;j++){if(String(entries[j].type||'').toLowerCase()!=='anime')continue;targets.push({kind:relation,mal:n(entries[j].mal_id,0)})}}
var out=[],seen={};for(var k=0;k<targets.length;k++){var t=targets[k];if(!t.mal||seen[t.kind+':'+t.mal])continue;seen[t.kind+':'+t.mal]=1;var y=await findAniHubByMal(t.mal);if(!y)continue;var prefix=t.kind==='prequel'?'⬅ Попередній сезон · ':'Наступний сезон ➡ · ';out.push(new MultimediaItem({title:prefix+titleOf(y),url:pageUrl(y),posterUrl:posterOf(y),type:'anime'}))}
return out}
globalThis.load=async function(url,cb){var base=null;try{base=await new Promise(function(resolve){baseLoad(url,resolve)});if(!base||!base.success||!base.data)return cb(base);var id=idFromPage(url);if(!id)return cb(base);var x=await getJson(API+'/anime/'+id,{'User-Agent':UA,'Accept':'application/json','Referer':manifest.baseUrl+'/'});if(!x)return cb(base);var recs=await recommendationsFor(x);if(!recs.length)return cb(base);var d=base.data;return cb({success:true,data:new MultimediaItem({title:d.title,url:d.url,posterUrl:d.posterUrl,bannerUrl:d.bannerUrl,type:d.type||'anime',description:d.description,episodes:d.episodes,recommendations:recs})})}catch(e){console.log('[AniHub recommendations] '+String(e));return cb(base||{success:false,error:'AniHub: '+String(e)})}}
}());

(function(){
var INTERNAL='https://anihub.in.ua/api';
var UA='Mozilla/5.0 (iPhone; CPU iPhone OS 18_0 like Mac OS X) AppleWebKit/605.1.15 Version/18.0 Mobile/15E148 Safari/604.1';
function n(v,d){var x=parseInt(v,10);return isNaN(x)?d:x}
function dec(s){return String(s==null?'':s).replace(/\\u0026/g,'&').replace(/\\\//g,'/').replace(/&amp;/g,'&').replace(/&quot;/g,'"').replace(/&#39;|&#039;/g,"'")}
function txt(s){return dec(s).replace(/<[^>]+>/g,'').replace(/\s+/g,' ').trim()}
function pick(o,ks,d){for(var i=0;i<ks.length;i++){var v=o&&o[ks[i]];if(v!==undefined&&v!==null&&v!=='')return v}return d}
function H(ref,accept,extra){var h={'User-Agent':UA,'Accept':accept||'application/json,text/plain,*/*','Referer':ref||manifest.baseUrl+'/'};try{h.Origin=new URL(ref||manifest.baseUrl+'/').origin}catch(e){}if(extra)for(var k in extra)h[k]=extra[k];return h}
async function raw(u,h){try{var r=await http_get(u,h||H()),b=r&&typeof r.body==='string'?r.body:'';return{body:b,status:r&&((r.statusCode||r.status))||0,error:''}}catch(e){return{body:'',status:0,error:String(e)}}}
function abs(u,base){u=dec(u).trim();if(!u)return'';if(/^https?:\/\//i.test(u))return u;if(u.indexOf('//')===0)return'https:'+u;try{return new URL(u,base||manifest.baseUrl+'/').toString()}catch(e){return''}}
function idFromPage(u){var m=String(u||'').match(/-(\d+)(?:[/?#]|$)/);if(m)return n(m[1],0);m=String(u||'').match(/\/anime\/(\d+)(?:[/?#]|$)/);return m?n(m[1],0):0}
function unpack(s){try{return JSON.parse(decodeURIComponent(String(s||'').slice('anihub:episode:'.length)))}catch(e){return null}}
function sha256(ascii){function rr(v,a){return(v>>>a)|(v<<(32-a))}var mp=Math.pow,mw=mp(2,32),i,j,res='',w=[],bits=ascii.length*8,h=sha256.h=sha256.h||[],k=sha256.k=sha256.k||[],pc=k.length,c={};for(var q=2;pc<64;q++)if(!c[q]){for(i=0;i<313;i+=q)c[i]=q;h[pc]=(mp(q,.5)*mw)|0;k[pc++]=(mp(q,1/3)*mw)|0}ascii+='\x80';while(ascii.length%64-56)ascii+='\x00';for(i=0;i<ascii.length;i++){j=ascii.charCodeAt(i);if(j>>8)return'';w[i>>2]|=j<<((3-i)%4)*8}w[w.length]=(bits/mw)|0;w[w.length]=bits;for(j=0;j<w.length;){var a=w.slice(j,j+=16),hh=h.slice(0);for(i=0;i<64;i++){var w15=a[i-15],w2=a[i-2],A=hh[0],E=hh[4],t1=hh[7]+(rr(E,6)^rr(E,11)^rr(E,25))+((E&hh[5])^((~E)&hh[6]))+k[i]+(a[i]=(i<16)?a[i]:((a[i-16]+(rr(w15,7)^rr(w15,18)^(w15>>>3))+a[i-7]+(rr(w2,17)^rr(w2,19)^(w2>>>10)))|0)),t2=(rr(A,2)^rr(A,13)^rr(A,22))+((A&hh[1])^(A&hh[2])^(hh[1]&hh[2]));hh=[(t1+t2)|0,A,hh[1],hh[2],(hh[3]+t1)|0,hh[4],hh[5],hh[6]]}for(i=0;i<8;i++)h[i]=(h[i]+hh[i])|0}for(i=0;i<8;i++)for(j=3;j+1;j--){var b=(h[i]>>(j*8))&255;res+=(b<16?'0':'')+b.toString(16)}return res}
function pad2(v){return v<10?'0'+v:String(v)}
function apiKey(off){var d=new Date(Date.now()+(off||0)*86400000),ds=d.getUTCFullYear()+'-'+pad2(d.getUTCMonth()+1)+'-'+pad2(d.getUTCDate());return sha256('Ukr@in1anAn1me-S3curity-Key-2025_'+ds)}
async function sources(id,season){var u=INTERNAL+'/anime/'+id+'/episode-sources?season='+season,ks=[apiKey(0),apiKey(-1),apiKey(1)];for(var i=0;i<ks.length;i++){var r=await raw(u,H(manifest.baseUrl+'/','application/json,text/plain,*/*',{'X-API-Key':ks[i],'X-Requested-With':'XMLHttpRequest'}));if(r.body)try{return JSON.parse(r.body)}catch(e){}}return null}
function provider(u){u=String(u||'');if(/uacdn\.online/i.test(u))return'UACDN';if(/ashdi\.vip/i.test(u))return'ASHDI';if(/fenix/i.test(u))return'FENIX';if(/moonanime|moon/i.test(u))return'MOON';return''}
function urls(s){var o=[],seen={},re=/(https?:\\?\/\\?\/[^"'\s<>]+)/ig,m;while((m=re.exec(String(s||'')))){var u=dec(m[1]).replace(/\\\//g,'/').replace(/[),;]+$/,'');if(provider(u)&&!seen[u]){seen[u]=1;o.push(u)}}return o}
function explicitEp(o){var v=pick(o,['episode_number','episode','number','ep','episodeNumber'],null);if(v===null||v===undefined||v==='')return null;var x=parseInt(v,10);return isNaN(x)?null:x}
function collectPlayers(node,ep,out,seen,depth){if(node==null||depth>14)return;if(typeof node==='string'){var a=urls(node);for(var i=0;i<a.length;i++)if(!seen[a[i]]){seen[a[i]]=1;out.push(a[i])}return}if(Array.isArray(node)){for(var j=0;j<node.length;j++)collectPlayers(node[j],ep,out,seen,depth+1);return}if(typeof node!=='object')return;var ee=explicitEp(node);if(ee!==null&&ee!==ep)return;for(var k in node){var v=node[k];if(typeof v==='string'&&/(url|src|link|iframe|player|embed|video|stream|file)/i.test(k)){var a2=urls(v);for(var q=0;q<a2.length;q++)if(!seen[a2[q]]){seen[a2[q]]=1;out.push(a2[q])}}}for(var z in node)collectPlayers(node[z],ep,out,seen,depth+1)}
function headers(ref,extra){var h={'User-Agent':UA,'Referer':ref||manifest.baseUrl+'/'};try{h.Origin=new URL(ref||manifest.baseUrl+'/').origin}catch(e){}if(extra)for(var k in extra)h[k]=extra[k];return h}
function add(out,u,label,ref,extra){u=dec(String(u||'')).trim().replace(/\\\//g,'/');if(/^https?:\/\//i.test(u)&&/\.(?:m3u8|mp4)(?:[?#]|$)/i.test(u))out.push(new StreamResult({url:u,source:'V13 '+label,headers:headers(ref,extra)}))}
function directMedia(s){var out=[],seen={},re=/(https?:\\?\/\\?\/[^"'\s<>]+?\.(?:m3u8|mp4)(?:\?[^"'\s<>]*)?)/ig,m;while((m=re.exec(String(s||'')))){var u=dec(m[1]).replace(/\\\//g,'/');if(!seen[u]){seen[u]=1;out.push(u)}}return out}
function assignedJson(s,marker){var p=String(s||'').indexOf(marker);if(p<0)return'';var a=String(s).slice(p+marker.length),st=a.indexOf('{');if(st<0)return'';var d=0,q=false,e=false;for(var i=st;i<a.length;i++){var c=a.charAt(i);if(q){if(e)e=false;else if(c==='\\')e=true;else if(c==='"')q=false;continue}if(c==='"'){q=true;continue}if(c==='{')d++;else if(c==='}'&&--d===0)return a.slice(st,i+1)}return''}
function playerFileValue(ph){var m=/\bfile\s*:/.exec(ph||'');if(!m)return null;var i=m.index+m[0].length,L=ph.length;while(i<L&&/\s/.test(ph.charAt(i)))i++;if(i>=L)return null;var q=ph.charAt(i);if(q==='"'||q==="'"||q==='`'){i++;var o='',esc=false;for(;i<L;i++){var c=ph.charAt(i);if(esc){o+=c;esc=false;continue}if(c==='\\'){esc=true;o+=c;continue}if(c===q)break;o+=c}return dec(o).replace(/\\(["'\/])/g,'$1')}if(q==='['){var st=i,d=0,str='',esc2=false;for(;i<L;i++){var ch=ph.charAt(i);if(str){if(esc2){esc2=false;continue}if(ch==='\\'){esc2=true;continue}if(ch===str)str='';continue}if(ch==='"'||ch==="'"||ch==='`'){str=ch;continue}if(ch==='[')d++;else if(ch===']'){d--;if(d===0)return dec(ph.slice(st,i+1))}}}return null}
function flat(node,out,path,pos){path=path||[];if(!node)return;if(Array.isArray(node)){for(var i=0;i<node.length;i++)flat(node[i],out,path,i+1);return}if(typeof node!=='object')return;var title=txt(node.title||''),next=path;if(node.folder&&title)next=path.concat([title]);if(node.file){var nums=title.match(/\d{1,3}/g),ep=nums&&nums.length?parseInt(nums[nums.length-1],10):(pos||1);out.push({number:ep,file:dec(node.file),label:path.join(' › ')||title||'ASHDI'})}if(node.folder)flat(node.folder,out,next,1)}
function addFile(out,file,label,ref){var r=dec(String(file||'').trim()),m,re=/\[([^\]]+)\](https?:\/\/[^,\s]+)/g,got=0;while((m=re.exec(r))!==null&&got<3){add(out,m[2],label+' '+m[1],ref);got++}if(!got&&/^https?:\/\//i.test(r))add(out,r,label,ref)}
function uacdnPayload(s){var m=String(s||'').match(/window\.__PLAYER_PAYLOAD__\s*=\s*(\{[\s\S]*?\});/);if(!m)return null;try{return JSON.parse(m[1])}catch(e){return null}}
async function resolveUacdn(player,page,ep){var out=[],r=await raw(player,H(page,'text/html,application/xhtml+xml,*/*')),p=r.body?uacdnPayload(r.body):null;if(!p)return out;var tr=Array.isArray(p.translations)?p.translations.slice():[];if(!tr.length)tr=[{id:p.translate,title:p.translateTitle||'UA'}];for(var i=0;i<tr.length&&out.length<3;i++){var t=tr[i];if(/субтит|\bsub\b|subbed/i.test(String(t.title||'')))continue;try{var season=parseInt(p.season,10)||1,body=JSON.stringify({id:parseInt(p.id,10)||0,translation:parseInt(t.id,10)||parseInt(p.translate,10)||0,season_number:p.is_serial?season:null,episode_number:p.is_serial?ep:null,force_cdn:String(p.force_cdn||''),turnstile_token:''}),api=new URL('/api/player/files',player).toString(),rr=await http_post(api,{'User-Agent':UA,'Accept':'application/json','Content-Type':'application/json','Referer':player,'Origin':new URL(player).origin},body),text=rr&&typeof rr.body==='string'?rr.body:'';if(!text)continue;var j=JSON.parse(text);if(j.file)addFile(out,j.file,'UACDN '+txt(t.title||p.translateTitle||'UA'),player)}catch(e){}}return out}
async function resolveAshdi(player,page,ep){var out=[],r=await raw(player,H(page,'text/html,application/xhtml+xml,*/*')),pf=r.body?playerFileValue(r.body):null;if(!pf)return out;if(/^https?:\/\//i.test(pf)){addFile(out,pf,'ASHDI',player);return out}try{var cfg=JSON.parse(pf),a=[];flat(cfg,a,[],1);for(var i=0;i<a.length&&out.length<3;i++)if(a[i].number===ep)addFile(out,a[i].file,'ASHDI '+a[i].label,player)}catch(e){}return out}
async function resolveFenix(player,page,ep){var out=[],r=await raw(player,H(page,'text/html,application/xhtml+xml,*/*')),s=r.body||'';if(!s)return out;var access={},aj=assignedJson(s,'window.FENIX_MEDIA_ACCESS');if(aj)try{access=JSON.parse(aj)||{}}catch(e){}var token=String(pick(access,['token','access_token','media_token'],'')||''),extra={};if(token){extra.Authorization='Bearer '+token;extra['X-Access-Token']=token}if(access.headers&&typeof access.headers==='object')for(var hk in access.headers)extra[hk]=String(access.headers[hk]);var pj=assignedJson(s,'window.FENIX_PLAYLIST')||assignedJson(s,'FENIX_PLAYLIST')||assignedJson(s,'window.__PLAYER_PAYLOAD__');if(pj)try{var pl=JSON.parse(pj),list=(pl.episodes||[]).concat(pl.mini_episodes||[]),entry=null;for(var i=0;i<list.length;i++){var en=n(pick(list[i],['number','episode','episode_number'],0),0);if(en===ep){entry=list[i];break}}if(!entry&&list.length===1)entry=list[0];if(entry){var tracks=entry.tracks||entry.sources||[];for(var j=0;j<tracks.length&&out.length<3;j++){var u=abs(pick(tracks[j],['hls_url','url','src','file'],''),player);if(token)try{var x=new URL(u);if(!x.searchParams.get('token'))x.searchParams.append('token',token);u=x.toString()}catch(e){}add(out,u,'FENIX'+(tracks[j].label?' '+tracks[j].label:''),player,extra)}}}catch(e){}if(!out.length){var dm=directMedia(s);for(var z=0;z<dm.length&&out.length<3;z++)add(out,dm[z],'FENIX',player,extra)}return out}
async function resolveMoon(player,page){var out=[],r=await raw(player,H(page,'text/html,application/xhtml+xml,*/*')),dm=directMedia(r.body||'');for(var i=0;i<dm.length&&out.length<3;i++)add(out,dm[i],'MOON',player);return out}
async function resolvePlayer(u,page,ep){var p=provider(u);if(p==='UACDN')return await resolveUacdn(u,page,ep);if(p==='ASHDI')return await resolveAshdi(u,page,ep);if(p==='FENIX')return await resolveFenix(u,page,ep);if(p==='MOON')return await resolveMoon(u,page);return[]}
function dedupe(a){var o=[],s={};for(var i=0;i<a.length;i++){var u=String(a[i]&&a[i].url||'');if(u&&!s[u]){s[u]=1;o.push(a[i])}}return o}
globalThis.loadStreams=async function(url,cb){try{var info=unpack(String(url||''));if(!info||!info.page)return cb({success:false,error:'AniHub v13: bad token'});var id=idFromPage(info.page),ep=n(info.episode,1),players=[],chosen=0;for(var season=1;season<=10;season++){var src=await sources(id,season);if(!src)continue;var c=[];collectPlayers(src,ep,c,{},0);if(c.length){players=c;chosen=season;break}}var out=[];for(var i=0;i<players.length&&i<8&&out.length<3;i++){var got=await resolvePlayer(players[i],info.page,ep);for(var j=0;j<got.length&&out.length<3;j++)out.push(got[j])}out=dedupe(out);console.log('[AniHub v13] id='+id+' season='+chosen+' ep='+ep+' players='+players.length+' streams='+out.length);if(!out.length)return cb({success:false,error:'AniHub v13: s='+chosen+' players='+players.length+' streams=0'});cb({success:true,data:out.slice(0,3)})}catch(e){cb({success:false,error:'AniHub v13: '+String(e)})}}
}());
